<?php

namespace WOTW\Bundle\SerialCatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialRepository extends EntityRepository
{
    public function findAllByNewest()
    {
        return $this->createQueryBuilder('s')
            ->orderBy('s.createdAt')
            ->getQuery()
            ;
    }
}
