parameters:
#    wotw_serial_catalog.example.class: WOTW\Bundle\SerialCatalogBundle\Example

services:
#    wotw_serial_catalog.example:
#        class: %wotw_serial_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
